import { google } from '@ai-sdk/google';
import { generateText } from 'ai';
import { env } from '../config/env';
import { logger } from '../config/logger';
import { StorageService } from './storage.service';

// Hero section image style types
export type HeroImageStyle =
  | 'abstract'
  | 'gradient-art'
  | 'illustration'
  | 'landscape'
  | 'product'
  | 'minimal'
  | 'geometric'
  | 'tech'
  | 'nature'
  | 'business';

export interface GenerateHeroImageRequest {
  prompt: string;
  style?: HeroImageStyle;
  includeText?: string;
  mood?: string;
  colorScheme?: string;
}

export interface GeneratedImage {
  imageUrl: string;
  storagePath: string;
  prompt: string;
  style: HeroImageStyle;
  mimeType: string;
  generatedAt: Date;
}

export class ImageGenerationService {
  private static model = google(env.GEMINI_IMAGE_MODEL);

  // Style-specific prompt enhancements for hero sections
  private static stylePrompts: Record<HeroImageStyle, string> = {
    abstract:
      'Create an abstract artistic composition with flowing shapes, dynamic forms, and harmonious colors. Modern and visually striking.',
    'gradient-art':
      'Design a beautiful gradient artwork with smooth color transitions, subtle textures, and a contemporary aesthetic. Perfect for modern web design.',
    illustration:
      'Create a custom digital illustration with clean lines, vibrant colors, and a professional look. Suitable for hero sections.',
    landscape:
      'Generate a stunning landscape image with dramatic lighting, rich colors, and depth. Inspiring and immersive.',
    product:
      'Create a clean product showcase setting with professional lighting, subtle shadows, and a minimal background. Premium and polished.',
    minimal:
      'Design a minimalistic composition with clean lines, ample white space, and subtle accents. Elegant and sophisticated.',
    geometric:
      'Create a geometric pattern with precise shapes, bold angles, and a modern color palette. Tech-forward and professional.',
    tech:
      'Generate a futuristic tech-inspired image with digital elements, glowing accents, and a cutting-edge feel. Innovative and dynamic.',
    nature:
      'Create a nature-inspired image with organic forms, earthy colors, and a serene atmosphere. Fresh and inviting.',
    business:
      'Design a professional business-themed image with corporate aesthetics, clean composition, and trustworthy vibes. Established and reliable.',
  };

  /**
   * Generate a hero section image using Gemini 2.0 Flash
   */
  static async generateHeroImage(
    request: GenerateHeroImageRequest,
    userId: string
  ): Promise<GeneratedImage> {
    try {
      const style = request.style || 'abstract';
      const enhancedPrompt = this.buildEnhancedPrompt(request);

      logger.info(`Generating hero image with style: ${style} for user: ${userId}`);

      const { files } = await generateText({
        model: this.model,
        providerOptions: {
          google: {
            responseModalities: ['TEXT', 'IMAGE'],
          },
        },
        messages: [
          {
            role: 'user',
            content: enhancedPrompt,
          },
        ],
      });

      if (!files || files.length === 0) {
        throw new Error('No image generated by Gemini');
      }

      // Get the generated image
      const generatedFile = files[0];
      const imageBuffer = Buffer.from(generatedFile.uint8Array);
      const mimeType = generatedFile.mediaType || 'image/png';
      const extension = mimeType.includes('png') ? 'png' : 'jpeg';

      // Upload to Supabase storage
      const { publicUrl, storagePath } = await this.uploadGeneratedImage(
        userId,
        imageBuffer,
        extension
      );

      logger.info(`Hero image generated and uploaded: ${storagePath}`);

      return {
        imageUrl: publicUrl,
        storagePath,
        prompt: request.prompt,
        style,
        mimeType,
        generatedAt: new Date(),
      };
    } catch (error) {
      logger.error('Error generating hero image:', error);
      throw error;
    }
  }

  /**
   * Generate multiple hero image variations
   */
  static async generateHeroImageVariations(
    request: GenerateHeroImageRequest,
    userId: string,
    count: number = 3
  ): Promise<GeneratedImage[]> {
    try {
      const variations: GeneratedImage[] = [];
      const styles: HeroImageStyle[] = this.getVariationStyles(request.style, count);

      // Generate images in sequence to avoid rate limiting
      for (const style of styles) {
        const variationRequest = { ...request, style };
        const image = await this.generateHeroImage(variationRequest, userId);
        variations.push(image);
      }

      logger.info(`Generated ${variations.length} hero image variations`);
      return variations;
    } catch (error) {
      logger.error('Error generating hero image variations:', error);
      throw error;
    }
  }

  /**
   * Generate an image with text overlay (great for ads, social posts, invitations)
   */
  static async generateImageWithText(
    prompt: string,
    text: string,
    userId: string,
    style: HeroImageStyle = 'minimal'
  ): Promise<GeneratedImage> {
    const request: GenerateHeroImageRequest = {
      prompt,
      style,
      includeText: text,
    };

    return this.generateHeroImage(request, userId);
  }

  /**
   * Edit an existing image using Gemini
   */
  static async editImage(
    imageUrl: string,
    editPrompt: string,
    userId: string
  ): Promise<GeneratedImage> {
    try {
      logger.info(`Editing image for user: ${userId}`);

      const { files } = await generateText({
        model: this.model,
        providerOptions: {
          google: {
            responseModalities: ['TEXT', 'IMAGE'],
          },
        },
        messages: [
          {
            role: 'user',
            content: [
              {
                type: 'image',
                image: new URL(imageUrl),
              },
              {
                type: 'text',
                text: editPrompt,
              },
            ],
          },
        ],
      });

      if (!files || files.length === 0) {
        throw new Error('No edited image generated');
      }

      const generatedFile = files[0];
      const imageBuffer = Buffer.from(generatedFile.uint8Array);
      const mimeType = generatedFile.mediaType || 'image/png';
      const extension = mimeType.includes('png') ? 'png' : 'jpeg';

      const { publicUrl, storagePath } = await this.uploadGeneratedImage(
        userId,
        imageBuffer,
        extension
      );

      logger.info(`Edited image uploaded: ${storagePath}`);

      return {
        imageUrl: publicUrl,
        storagePath,
        prompt: editPrompt,
        style: 'abstract',
        mimeType,
        generatedAt: new Date(),
      };
    } catch (error) {
      logger.error('Error editing image:', error);
      throw error;
    }
  }

  /**
   * Build an enhanced prompt for hero section images
   */
  private static buildEnhancedPrompt(request: GenerateHeroImageRequest): string {
    const style = request.style || 'abstract';
    const stylePrompt = this.stylePrompts[style];

    let prompt = `${stylePrompt}\n\nUser request: ${request.prompt}`;

    if (request.mood) {
      prompt += `\n\nMood/Atmosphere: ${request.mood}`;
    }

    if (request.colorScheme) {
      prompt += `\n\nColor scheme: ${request.colorScheme}`;
    }

    if (request.includeText) {
      prompt += `\n\nInclude this text in the image (render clearly and legibly): "${request.includeText}"`;
    }

    // Add hero section specific requirements
    prompt += `\n\nRequirements:
- High resolution and professional quality
- Suitable for website hero section (wide aspect ratio preferred)
- Visually balanced with space for overlaying text if needed
- Modern and contemporary design aesthetic
- Clean and not overly busy`;

    return prompt;
  }

  /**
   * Get variation styles based on the primary style
   */
  private static getVariationStyles(primaryStyle: HeroImageStyle | undefined, count: number): HeroImageStyle[] {
    const allStyles: HeroImageStyle[] = [
      'abstract',
      'gradient-art',
      'illustration',
      'landscape',
      'minimal',
      'geometric',
      'tech',
      'nature',
      'business',
      'product',
    ];

    if (!primaryStyle) {
      return allStyles.slice(0, count);
    }

    // Start with primary style and add related styles
    const relatedStyles: Record<HeroImageStyle, HeroImageStyle[]> = {
      abstract: ['gradient-art', 'geometric', 'minimal'],
      'gradient-art': ['abstract', 'minimal', 'geometric'],
      illustration: ['abstract', 'nature', 'business'],
      landscape: ['nature', 'abstract', 'minimal'],
      product: ['minimal', 'business', 'tech'],
      minimal: ['abstract', 'gradient-art', 'geometric'],
      geometric: ['abstract', 'tech', 'minimal'],
      tech: ['geometric', 'abstract', 'minimal'],
      nature: ['landscape', 'abstract', 'minimal'],
      business: ['minimal', 'product', 'geometric'],
    };

    const styles: HeroImageStyle[] = [primaryStyle];
    const related = relatedStyles[primaryStyle] || [];

    for (const style of related) {
      if (styles.length < count && !styles.includes(style)) {
        styles.push(style);
      }
    }

    // Fill remaining with other styles
    for (const style of allStyles) {
      if (styles.length < count && !styles.includes(style)) {
        styles.push(style);
      }
    }

    return styles.slice(0, count);
  }

  /**
   * Upload generated image to Supabase storage
   */
  private static async uploadGeneratedImage(
    userId: string,
    imageBuffer: Buffer,
    extension: string
  ): Promise<{ publicUrl: string; storagePath: string }> {
    // Use the existing StorageService but with a different folder for generated images
    const { v4: uuidv4 } = await import('uuid');
    const fileName = `generated-${uuidv4()}`;

    // We'll use png format for consistency
    return StorageService.uploadGradientImage(
      userId,
      imageBuffer,
      extension === 'png' ? 'png' : 'png', // Force PNG for now
      fileName
    );
  }

  /**
   * Get available hero image styles
   */
  static getAvailableStyles(): { style: HeroImageStyle; description: string }[] {
    return Object.entries(this.stylePrompts).map(([style, description]) => ({
      style: style as HeroImageStyle,
      description: description.split('.')[0] + '.', // Just the first sentence
    }));
  }
}
